name: server

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: py${{ matrix.python-version }}-jira${{ matrix.jira-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
        jira-version: [8.17.1]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Start Jira docker instance
        run: docker run -dit -p 2990:2990 --name jira addono/jira-software-standalone --version ${{ matrix.jira-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Setup the Pip cache
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: >-
            ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}-${{
            hashFiles('setup.py') }}-${{ hashFiles('tox.ini') }}-${{
            hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          sudo apt-get update; sudo apt-get install gcc libkrb5-dev
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-gh-actions

      - name: Lint with tox
        run: tox -e lint

      - name: Test with tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v3.1.0
        with:
          file: ./coverage.xml
          name: ${{ runner.os }}-${{ matrix.python-version }}

      - name: Run tox packaging
        run: tox -e packaging

      - name: Make docs
        run: tox -e docs
