name: cloud

on:
  workflow_call:
    secrets:
      CLOUD_ADMIN:
        required: true
      CLOUD_ADMIN_TOKEN:
        required: true
      CLOUD_USER:
        required: true
      CLOUD_USER_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    environment: cloud
    name: py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # We only test a single version to prevent concurrent
        # running of tests influencing one another
        python-version: ["3.8"]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Setup the Pip cache
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: >-
            ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}-${{
            hashFiles('setup.py') }}-${{ hashFiles('tox.ini') }}-${{
            hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          sudo apt-get update; sudo apt-get install gcc libkrb5-dev
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-gh-actions

      - name: Test with tox
        run: tox -e py38 -- -m allow_on_cloud
        env:
          CI_JIRA_TYPE: CLOUD
          CI_JIRA_CLOUD_ADMIN: ${{ secrets.CLOUD_ADMIN }}
          CI_JIRA_CLOUD_ADMIN_TOKEN: ${{ secrets.CLOUD_ADMIN_TOKEN }}
          CI_JIRA_CLOUD_USER: ${{ secrets.CLOUD_USER }}
          CI_JIRA_CLOUD_USER_TOKEN: ${{ secrets.CLOUD_USER_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v3.1.0
        with:
          file: ./coverage.xml
          name: ${{ runner.os }}-${{ matrix.python-version }}-Cloud
